### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by hessijames79** [linuxserver/docker-babybuddy#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container does not restart any more.

Logs shows
`ModuleNotFoundError: No module named 'MySQLdb'`

### Expected Behavior

Babybuddy should start

### Steps To Reproduce

docker run -d --name babybuddy --restart=always \
	-p 88:8000 \
	-v babybuddy_data:/config \
	-e TZ=Europe/Berlin \
	-e CSRF_TRUSTED_ORIGINS=http://127.0.0.1:88,REDACTED \
	-e DB_ENGINE=django.db.backends.mysql \
	-e DB_HOST=mariadb.REDACTED \
	-e DB_PORT=3306 \
	-e DB_NAME=babybuddy \
	-e DB_USER=babybuddy \
	-e DB_PASSWORD=REDACTED \
	lscr.io/linuxserver/babybuddy:latest

### Environment

```markdown
- OS: Debian GNU/Linux 11
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d --name babybuddy --restart=always \
	-p 88:8000 \
	-v babybuddy_data:/config \
	-e TZ=Europe/Berlin \
	-e CSRF_TRUSTED_ORIGINS=http://127.0.0.1:88,REDACTED \
	-e DB_ENGINE=django.db.backends.mysql \
	-e DB_HOST=mariadb.REDACTED \
	-e DB_PORT=3306 \
	-e DB_NAME=babybuddy \
	-e DB_USER=babybuddy \
	-e DB_PASSWORD=REDACTED \
	lscr.io/linuxserver/babybuddy:latest
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
BabyBuddy: https://github.com/sponsors/cdubz

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

using keys found in /config/keys
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/www/public/manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/lsiopy/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/lsiopy/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/lsiopy/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/www/public/babybuddy/models.py", line 13, in <module>
    from rest_framework.authtoken.models import Token
  File "/lsiopy/lib/python3.11/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/lsiopy/lib/python3.11/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/lsiopy/lib/python3.11/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/lsiopy/lib/python3.11/site-packages/django/db/models/options.py", line 243, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
```

**Comment by thespad** [comment]
I think I know the issue, let me do some tests to confirm.

**Comment by thespad** [comment]
Could you please try `lspipepr/babybuddy:v1.16.0-pkg-f5c947f3-dev-39b990f84978127bc3c35c64958a4b15a40705b3-pr-30` and see if it fixes your issue.

**Comment by hessijames79** [comment]
Sure:

using keys found in /config/keys
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: Error loading shared library libmariadb.so.3: No such file or directory (needed by /lsiopy/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-x86_64-linux-musl.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/www/public/manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/lsiopy/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/lsiopy/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/lsiopy/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/www/public/babybuddy/models.py", line 13, in <module>
    from rest_framework.authtoken.models import Token
  File "/lsiopy/lib/python3.11/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/lsiopy/lib/python3.11/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/lsiopy/lib/python3.11/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/lsiopy/lib/python3.11/site-packages/django/db/models/options.py", line 243, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/lsiopy/lib/python3.11/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
                  ^^^^^^
NameError: name '_mysql' is not defined
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: Error loading shared library libmariadb.so.3: No such file or directory (needed by /lsiopy/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-x86_64-linux-musl.so)

**Comment by thespad** [comment]
Oops, forgot the connector libs. I'll add them.

**Comment by thespad** [comment]
OK, please try `lspipepr/babybuddy:v1.16.0-pkg-f5c947f3-dev-de0029c0cc906b571efc5309bf72d84c2da3a322-pr-30`

**Comment by hessijames79** [comment]
Lovely, works perfectly now.

```
2023-06-02T12:17:45.064707574Z [migrations] started
2023-06-02T12:17:45.101100902Z [migrations] 01-nginx-site-confs-default: skipped
2023-06-02T12:17:45.103887862Z [migrations] 02-default-location: skipped
2023-06-02T12:17:45.103927882Z [migrations] done
2023-06-02T12:17:45.144143532Z usermod: no changes
2023-06-02T12:17:45.145726919Z ───────────────────────────────────────
2023-06-02T12:17:45.145758553Z 
2023-06-02T12:17:45.145767694Z       ██╗     ███████╗██╗ ██████╗ 
2023-06-02T12:17:45.145775751Z       ██║     ██╔════╝██║██╔═══██╗
2023-06-02T12:17:45.145783426Z       ██║     ███████╗██║██║   ██║
2023-06-02T12:17:45.145790876Z       ██║     ╚════██║██║██║   ██║
2023-06-02T12:17:45.145798283Z       ███████╗███████║██║╚██████╔╝
2023-06-02T12:17:45.145805685Z       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
2023-06-02T12:17:45.145812970Z 
2023-06-02T12:17:45.145819973Z    Brought to you by linuxserver.io
2023-06-02T12:17:45.145826992Z ───────────────────────────────────────
2023-06-02T12:17:45.145995001Z 
2023-06-02T12:17:45.146008055Z To support the app dev(s) visit:
2023-06-02T12:17:45.147430600Z BabyBuddy: https://github.com/sponsors/cdubz
2023-06-02T12:17:45.147723729Z 
2023-06-02T12:17:45.147760727Z To support LSIO projects visit:
2023-06-02T12:17:45.147771744Z https://www.linuxserver.io/donate/
2023-06-02T12:17:45.147779702Z 
2023-06-02T12:17:45.147787236Z ───────────────────────────────────────
2023-06-02T12:17:45.147795719Z GID/UID
2023-06-02T12:17:45.147802987Z ───────────────────────────────────────
2023-06-02T12:17:45.151501493Z 
2023-06-02T12:17:45.151539515Z User UID:    911
2023-06-02T12:17:45.151550132Z User GID:    911
2023-06-02T12:17:45.151558040Z ───────────────────────────────────────
2023-06-02T12:17:45.151566370Z 
2023-06-02T12:17:45.341465666Z using keys found in /config/keys
2023-06-02T12:17:49.434454067Z Operations to perform:
2023-06-02T12:17:49.434532283Z   Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, sessions
2023-06-02T12:17:49.434543274Z Running migrations:
2023-06-02T12:17:49.434551072Z   No migrations to apply.
2023-06-02T12:17:49.434583661Z   Your models in app(s): 'babybuddy' have changes that are not yet reflected in a migration, and so won't be applied.
2023-06-02T12:17:49.434592953Z   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
2023-06-02T12:17:51.198529994Z Cache table 'cache_default' already exists.
2023-06-02T12:17:51.563454201Z [custom-init] No custom files found, skipping...
2023-06-02T12:17:52.022430454Z [2023-06-02 14:17:52 +0200] [227] [INFO] Starting gunicorn 20.1.0
2023-06-02T12:17:52.023099975Z [2023-06-02 14:17:52 +0200] [227] [INFO] Listening at: http://127.0.0.1:3000 (227)
2023-06-02T12:17:52.023226667Z [2023-06-02 14:17:52 +0200] [227] [INFO] Using worker: gthread
2023-06-02T12:17:52.027920971Z [2023-06-02 14:17:52 +0200] [258] [INFO] Booting worker with pid: 258
2023-06-02T12:17:52.090459312Z [2023-06-02 14:17:52 +0200] [259] [INFO] Booting worker with pid: 259
2023-06-02T12:17:52.656281126Z [ls.io-init] done.
```

Are the migration messages a problem as well? Have been seeing them long before the main issue appeared.

Patrick

**Comment by thespad** [comment]
I'm not sure about the migration messages, I would open an issue with the upstream project and ask them. We certainly *can* add a makemigrations step to the init if necessary but I can't find anything in the docs to suggest it should be.

**Comment by hessijames79** [comment]
Ok. Thank you again.
