### ISSUE TITLE
Image ARM doesn't work

### ISSUE THREAD

**Issue by RobinLambertini** [linuxserver/docker-babybuddy#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The application should works fine after the docker run on my raspberry 4 : 

```bash
docker run -d \
  --name=babybuddy \
  -e TZ=Europe/London \
  -p 8000:8000 \
  -v /home/pi/baby:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/babybuddy:arm64v8-latest
```

## Current Behavior
I've the error message : 

```bash
standard_init_linux.go:211: exec user process caused "exec format error"
```` 
Should mean the image is not ARMx64 but AMDx64

## Steps to Reproduce

1. Run the docker run and watch the logs

## Environment
**OS:** Raspbian GNU/Linux 10 (buster)
**CPU architecture:** arm64
**How docker service was installed:**

From the official way and their documentation

## Command used to create docker container (run/create/compose/screenshot)

Informations above

## Docker logs

Informations above

**Comment by Roxedus** [comment]
What does `uname -m` and `dpkg --print-architecture` show?

**Comment by RobinLambertini** [comment]
Here are the results : 

```bash
pi@raspberrypi:~/baby $ uname -m
armv7l
pi@raspberrypi:~/baby $ dpkg --print-architecture
armhf
```

**Comment by Roxedus** [comment]
Cool. So you have a 32bit kernel(raspberry OS ships with this as default), and need to use a arm32 image, like our armhf tags.

Alternatively you can reinstall to a 64 bit os.

**Comment by RobinLambertini** [comment]
Indeed, I'm a little bit dumb 👎 

I tried : 

```bash
docker run -d \
  --name=babybuddy \
  -e TZ=Europe/London \
  -p 8000:8000 \
  -v /home/pi/baby:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/babybuddy:arm32v7-latest
````
And I got this : 

```bash
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
Current thread 0xb6f6e390 (most recent call first):
<no Python frame>
```

**Comment by Roxedus** [comment]
Ah yes, another Raspberry OS thing. Your logs should have a message encapsulated by `@`s, which has a link to how to solve it.

**Comment by aptalca** [comment]
By the way, you don't need to specify the arch. If you simply pull `linuxserver/babybuddy`, it should automatically use the correct image for your arch

**Comment by RobinLambertini** [comment]
You was right, there was a link : https://docs.linuxserver.io/faq#libseccomp
Downloaded the .deb and installed it.

Alright, thanks you @aptalca

But got new errors : 

```bash
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
BabyBuddy: https://github.com/sponsors/cdubz
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Traceback (most recent call last):
  File "/app/babybuddy/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/usr/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/babybuddy/babybuddy/admin.py", line 3, in <module>
    from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 11, in <module>
    from django.contrib.auth.tokens import default_token_generator
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/tokens.py", line 117, in <module>
    default_token_generator = PasswordResetTokenGenerator()
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/tokens.py", line 18, in __init__
    self.secret = self.secret or settings.SECRET_KEY
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**Comment by aptalca** [comment]
Try deleting the config folder and recreating the container. It looks like the previous erroneous start saved an invalid secret key.

**Comment by RobinLambertini** [comment]
I tried but it doesn't work for the moment.
After the same errors above, I got this : 

```bash
[2021-08-30 15:30:54 +0200] [337] [INFO] Worker exiting (pid: 337)
[2021-08-30 15:30:54 +0200] [333] [WARNING] Worker with pid 337 was terminated due to signal 15
[2021-08-30 15:30:54 +0200] [333] [INFO] Shutting down: Master
[2021-08-30 15:30:54 +0200] [333] [INFO] Reason: Worker failed to boot.
[2021-08-30 15:30:55 +0200] [339] [INFO] Starting gunicorn 20.1.0
[2021-08-30 15:30:55 +0200] [339] [INFO] Listening at: http://0.0.0.0:8000 (339)
[2021-08-30 15:30:55 +0200] [339] [INFO] Using worker: gthread
[2021-08-30 15:30:55 +0200] [342] [INFO] Booting worker with pid: 342
[2021-08-30 15:30:55 +0200] [343] [INFO] Booting worker with pid: 343
```

**Comment by aptalca** [comment]
It suggests it's working.

Post the full log to be sure

**Comment by RobinLambertini** [comment]
I've a loop :
[errors.log](https://github.com/linuxserver/docker-babybuddy/files/7077159/errors.log)

EDIT : I precise the application is not available on the webui

**Comment by Shaun-Harrison** [comment]
Hello

I'm getting an error when trying to run the container on a RPI3 running `armv7l` & `armhf`

My docker-compose is 

```
version: "2.1"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:arm32v7-latest
    container_name: babybuddy
    environment:
      - TZ=Europe/London
    volumes:
      - ./appdata:/config
    ports:
      - 10405:8000
    restart: unless-stopped
```


Here is the output from the container logs

```
Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
BabyBuddy: https://github.com/sponsors/cdubz

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
**** No secret key found, generating one ****
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, easy_thumbnails, sessions
Running migrations:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 68, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/lib/python3.9/site-packages/django/db/backends/sqlite3/schema.py", line 36, in __exit__
    super().__exit__(exc_type, exc_value, traceback)
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 120, in __exit__
    self.atomic.__exit__(exc_type, exc_value, traceback)
  File "/usr/lib/python3.9/site-packages/django/db/transaction.py", line 246, in __exit__
    connection.commit()
  File "/usr/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/usr/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/babybuddy/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/babybuddy/babybuddy/management/commands/migrate.py", line 10, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/lib/python3.9/site-packages/django/db/migrations/executor.py", line 91, in migrate
    self.recorder.ensure_schema()
  File "/usr/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked
```

**Comment by thespad** [comment]
Please open a new issue rather than tacking it onto an existing, different one.
